spring.application.name=DeliveryService

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/keystone-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:keystone1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:keystone123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT
JWT_SECRET=${JWT_SECRET:change-this-secret-in-production}
JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:3600000}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html